name: build-and-deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: cd ./app && npm install

      - name: Build the app
        run: cd ./app && npm run build
